name: test app
on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install go 
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - name: Install deps
        run: |
          export GOPROXY=direct
          go mod tidy
          go mod download
      - name: Install linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4
      - name: Lint
        run: sudo /home/ryo/go/bin/golangci-lint run ./...

  test:
    needs: [ lint ]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install go 
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - name: Install deps
        run: |
          export GOPROXY=direct
          go mod tidy
          go mod download
      - name: Test
        run: make test
