name: test app
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install go 
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - name: Install deps
        run: |
          go mod tidy
          go mod download
      - name: Install linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4
          export PATH="$HOME/go/bin:$PATH"
      - name: Lint
        run: golangci-lint run ./...

  test:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install go 
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.4'
      - name: Install deps
        run: |
          go mod tidy
          go mod download
      - name: Test
        run: make test

  docker-build:
    needs: [ lint, test]
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_NAME }}:latest

  deploy:
    needs: docker-build
    runs-on: self-hosted
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER_IP }}
        username: ${{ secrets.DEPLOYMENT_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATEKEY }}
        script: /usr/bin/deploy_app.sh
        envs:
          - DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          - DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          - DOCKERHUB_REPO_NAME: ${{ secrets.DOCKERHUB_REPO_NAME }}
